inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'config/deploy/*.rb'
    - 'config/environments/*.rb'
    - 'vendor/**/*'

# because it's silly to care
Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
