version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.2.2
  browser-tools: circleci/browser-tools@1.3.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          context: dlss
      - ruby-rails/test-gem:
          name: test
          context: dlss
          before-test:
            - browser-tools/install-chrome
            - run:
                name: Install puppeteer
                command: yarn install
            - run:
                name: Install exiftool
                command: curl -L http://cpanmin.us | perl - --sudo Image::ExifTool
            - run:
                name: Install libvips
                command: sudo apt-get update && sudo apt-get install -y libvips
            - setup_remote_docker
            - run:
                name: Install Kakadu
                command: |
                  curl https://kakadusoftware.com/wp-content/uploads/KDU841_Demo_Apps_for_Linux-x86-64_231117.zip --output kakadu.zip
                  unzip kakadu.zip
                  mv KDU841_Demo_Apps_for_Linux-x86-64_231117 kakadu
                  sudo cp kakadu/*.so /usr/lib
                  sudo cp kakadu/* /usr/bin
