"wasCrawlPreassemblyWF_default,wasDisseminationWF_default,wasSeedDisseminationWF_default,wasSeedPreassemblyWF_default": 10
# Running a single worker for wasCrawlDisseminationWF_default to avoid possible conflicts when manipulating CDX indexes.
"wasCrawlDisseminationWF_default": 1
