ssl:
  cert_file: ~
  key_file: ~
  key_pass: ~

solr:
  url: ~

dor_services:
  url:  'https://dor-services-test.stanford.test'
  token: secret-token

was_crawl:
  source_path: '/was_unaccessioned_data/jobs/' # the root for the storage for the input directory
  staging_path: '/dor/workspace/'  # the root for the storage for DRUID tree that will be the input to AssemblyWF
  dedicated_lane: 'default'

was_crawl_dissemination:
  main_cdxj_file: "/web-archiving-stacks/data/indexes/cdxj/level0.cdxj"
  stacks_collections_path: "/web-archiving-stacks/data/collections/"

cdxj_indexer:
  bin: /opt/app/was/.local/bin/cdxj-indexer
  working_directory: /web-archiving-stacks/data/indexes/cdxj_working
  backup_directory: /web-archiving-stacks/data/indexes/cdxj_backup
  main_cdxj_file: /web-archiving-stacks/data/indexes/cdxj/level0.cdxj
  url: http://localhost/was/cdx?url=

was_seed:
  workspace_path: '/dor/workspace/'  #the root for the storage for DRUID tree that will be the input to AssemblyWF
  staging_path: '/was_unaccessioned_data/seed/'
  wayback_uri: 'https://swap.stanford.edu'

chrome_path: /usr/bin/google-chrome
workflow:
  url: https://example.com/workflow/
  logfile: 'log/workflow_service.log'
  shift_age: 'weekly'
  timeout: 60

redis:
  url: ~
