fedora:
  url: ~

ssl:
  cert_file: ~
  key_file: ~
  key_pass: ~

solr:
  url: ~

dor_services:
  url:  'https://dor-services-test.stanford.test'
  token: secret-token

was_crawl:
  source_path: '/was_unaccessioned_data/jobs/' # the root for the storage for the input directory
  staging_path: '/dor/workspace/'  # the root for the storage for DRUID tree that will be the input to AssemblyWF
  extracted_metadata_xml_location: 'tmp'
  java_heap_size: '-Xmx2048m'
  dedicated_lane: 'default'

was_crawl_dissemination:
  java_heap_size: '-Xmx1024m'
  cdx_working_directory: "/web-archiving-stacks/data/indices/cdx_working/"
  cdx_backup_directory: "/web-archiving-stacks/data/indices/cdx_backup/"
  main_cdx_file: "/web-archiving-stacks/data/indices/cdx/level0.cdx"

  path_working_directory: "/web-archiving-stacks/data/indices/path_working/"
  main_path_index_file: "/web-archiving-stacks/data/indices/path/path-index.txt"

  cdx_indexer_script: "jar/openwayback/bin/cdx-indexer"
  stacks_collections_path: "/web-archiving-stacks/data/collections/"
  sort_env_vars: "TMPDIR=/web-archiving-stacks/data/tmp/ LC_ALL=C"

cdxj_indexer:
  working_directory: /web-archiving-stacks/data/indexes/cdxj_working
  backup_directory: /web-archiving-stacks/data/indexes/cdxj_backup
  main_cdxj_file: /web-archiving-stacks/data/indexes/cdxj/level0.cdxj

was_seed:
  workspace_path: '/dor/workspace/'  #the root for the storage for DRUID tree that will be the input to AssemblyWF
  staging_path: '/was_unaccessioned_data/seed/'
  wayback_uri: 'https://swap.stanford.edu'

chrome_path: /usr/bin/google-chrome
workflow:
  url: https://example.com/workflow/
  logfile: 'log/workflow_service.log'
  shift_age: 'weekly'
  timeout: 60

redis:
  url: ~
