# Put each of your robots here and they will be included via config/boot'
require 'was/robots/base'

require 'was_crawl_dissemination/cdx_generator'
require 'was_crawl_dissemination/cdx_merge_sort_publish'
require 'was_crawl_dissemination/path_indexer'
require 'was_crawl_preassembly/build_was_crawl_druid_tree'
require 'was_crawl_preassembly/content_metadata_generator'
require 'was_crawl_preassembly/desc_metadata_generator'
require 'was_crawl_preassembly/end_was_crawl_preassembly'
require 'was_crawl_preassembly/metadata_extractor'
require 'was_crawl_preassembly/technical_metadata_generator'
require 'was_dissemination/start_special_dissemination'
require 'was_seed_dissemination/update_thumbnail_generator'
require 'was_seed_preassembly/content_metadata_generator'
require 'was_seed_preassembly/desc_metadata_generator'
require 'was_seed_preassembly/thumbnail_generator'
require 'was_seed_preassembly/end_was_seed_preassembly'
